/*
	calcclient.cpp

	Example calculator service client in C++

	Service definitions in calc.h (not generated by wsdl2h, but similar)

	$ soapcpp2 -i calc.h
	$ cc -o calcclient calcclient.cpp stdsoap2.cpp soapC.cpp soapcalcProxy.cpp
	where stdsoap2.cpp is in the 'gsoap' directory, or use libgsoap++:
	$ cc -o calcclient calcclient.cpp soapC.cpp soapcalcProxy.cpp -lgsoap++

--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2001-2008, Robert van Engelen, Genivia, Inc. All Rights Reserved.
This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org
--------------------------------------------------------------------------------
A commercial use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapBFCPServiceProxy.h"
#include "BFCPService.nsmap"

const char server[] = "http://localhost:8011/";

int main(int argc, char **argv)
{ 
  ns__ErrorCode errorCode = ns__ErrorCode::kNoError;
  BFCPServiceProxy calc(SOAP_C_UTFSTRING | SOAP_IO_KEEPALIVE);
  calc.soap_endpoint = server;
  char ch;
  std::cin >> ch;
  switch (ch)
  {
    case 'c':
      calc.start(ns__AddrFamily::kIPv4, 7890, true, 2, 30.0, &errorCode);
      break;
    case 'y':
      calc.stop(&errorCode);
      break;
    case 'i':
      calc.addConference(100, 3, ns__Policy::kAutoAccept, 120, &errorCode);
      break;
    case 'd':
      calc.removeConference(100, &errorCode);
      break;
    case 'a':
      calc.addFloor(100, 11, 2, -1.0, &errorCode);
      break;
    case 'f':
      calc.removeFloor(100, 11, &errorCode);
      break;
    case 'j':
      calc.addUser(100, 1, "user1", "", &errorCode);
      break;
    case 'k':
      calc.removeUser(100, 1, &errorCode);
      break;
    case 'q':
      calc.quit();
      break;
    default:
      fprintf(stderr, "Unknown command\n");
      exit(0);
  }
  printf("Error: %d\n", errorCode);
  if (calc.error)
    calc.soap_stream_fault(std::cerr);
  return 0;
}

